### ISSUE TITLE
Mixin-Deep SNYK Prototype Pollution

### ISSUE THREAD

**Issue by cnnranderson** [chris-feist/serverless-plugin-composed-vars#7]
Pipeline went down recently because there was a critical update to mixin-deep dependency (now on 2.0.1, due to a prototype pollution bug).

I can make a quick PR, or if you'd prefer to update it yourself, that'd be great! All that needs to be done is update mixin-deep to 2.0.1.

**Comment by chris-feist** [comment]
@cnnranderson I published 1.0.3 that uses the latest mixin-deep
